### ISSUE TITLE
Search shows results count but unable to navigate

### ISSUE THREAD

**Issue by goodev2021** [mapozyan/caps#4]
The search results just shows the count, unable to navigate to the search results

The keyword is not getting displayed inside the contents of the book

Will it just says the keyword exist in a book or we can able to navigate the search results and keyword will get highlighted on opening the book. 

Options would be great

1. search results count and books found to be listed
2. on clicking the book, the keyword should get automatically highlighted in all the occurences of the book
3. easy navigation with previous and next would be easier to walk through the search results

**Comment by mapozyan** [comment]
1. Maybe I misunderstood what list you mean but its basically the main Calibre window where you can see the list of books that are found.
2. I am afraid that's not possible because we have not much control over specific document (say, PDF) viewer.
3. Same here: once we ended up opening a dedicated program we have no other way to navigate but close it and return back to Calibre.
